#pragma once

#include "displaycontrol.h"
#include "displaystatus.h"
#include "backgroundcontrol.h"
#include "backgroundoffset.h"
#include "backgroundreference.h"
#include "backgroundparameter.h"
#include "windowrange.h"
#include "windowinside.h"
#include "windowoutside.h"
#include "mosaic.h"
#include "blendcontrol.h"
#include "blendalpha.h"
#include "blendfade.h"
#include "keycontrol.h"
#include "waitcontrol.h"
