#pragma once

#include "io/displaycontrol.h"
#include "io/displaystatus.h"
#include "io/backgroundcontrol.h"
#include "io/backgroundoffset.h"
#include "io/backgroundreference.h"
#include "io/backgroundparameter.h"
#include "io/windowrangeh.h"
#include "io/windowrangev.h"
#include "io/windowinside.h"
#include "io/windowoutside.h"
#include "io/mosaic.h"
#include "io/blendcontrol.h"
#include "io/blendalpha.h"
#include "io/blendfade.h"

#include "other/keycontrol.h"
#include "other/waitcontrol.h"
#include "other/timercontrol.h"
#include "other/timerdata.h"
#include "other/interrupt.h"
