#pragma once

#include "backgroundcontrol.h"
#include "backgroundoffset.h"
#include "backgroundparameter.h"
#include "backgroundreference.h"
#include "blendalpha.h"
#include "blendcontrol.h"
#include "blendfade.h"
#include "displaycontrol.h"
#include "displaystatus.h"
#include "keycontrol.h"
#include "mosaic.h"
#include "waitcontrol.h"
#include "windowrange.h"
#include "window.h"
