#include "arm.h"

ARM::HandlerThumb ARM::lut_thumb[1024] =
{
    &ARM::Thumb_MoveShiftedRegister< 0, 0>,
    &ARM::Thumb_MoveShiftedRegister< 1, 0>,
    &ARM::Thumb_MoveShiftedRegister< 2, 0>,
    &ARM::Thumb_MoveShiftedRegister< 3, 0>,
    &ARM::Thumb_MoveShiftedRegister< 4, 0>,
    &ARM::Thumb_MoveShiftedRegister< 5, 0>,
    &ARM::Thumb_MoveShiftedRegister< 6, 0>,
    &ARM::Thumb_MoveShiftedRegister< 7, 0>,
    &ARM::Thumb_MoveShiftedRegister< 8, 0>,
    &ARM::Thumb_MoveShiftedRegister< 9, 0>,
    &ARM::Thumb_MoveShiftedRegister<10, 0>,
    &ARM::Thumb_MoveShiftedRegister<11, 0>,
    &ARM::Thumb_MoveShiftedRegister<12, 0>,
    &ARM::Thumb_MoveShiftedRegister<13, 0>,
    &ARM::Thumb_MoveShiftedRegister<14, 0>,
    &ARM::Thumb_MoveShiftedRegister<15, 0>,
    &ARM::Thumb_MoveShiftedRegister<16, 0>,
    &ARM::Thumb_MoveShiftedRegister<17, 0>,
    &ARM::Thumb_MoveShiftedRegister<18, 0>,
    &ARM::Thumb_MoveShiftedRegister<19, 0>,
    &ARM::Thumb_MoveShiftedRegister<20, 0>,
    &ARM::Thumb_MoveShiftedRegister<21, 0>,
    &ARM::Thumb_MoveShiftedRegister<22, 0>,
    &ARM::Thumb_MoveShiftedRegister<23, 0>,
    &ARM::Thumb_MoveShiftedRegister<24, 0>,
    &ARM::Thumb_MoveShiftedRegister<25, 0>,
    &ARM::Thumb_MoveShiftedRegister<26, 0>,
    &ARM::Thumb_MoveShiftedRegister<27, 0>,
    &ARM::Thumb_MoveShiftedRegister<28, 0>,
    &ARM::Thumb_MoveShiftedRegister<29, 0>,
    &ARM::Thumb_MoveShiftedRegister<30, 0>,
    &ARM::Thumb_MoveShiftedRegister<31, 0>,
    &ARM::Thumb_MoveShiftedRegister< 0, 1>,
    &ARM::Thumb_MoveShiftedRegister< 1, 1>,
    &ARM::Thumb_MoveShiftedRegister< 2, 1>,
    &ARM::Thumb_MoveShiftedRegister< 3, 1>,
    &ARM::Thumb_MoveShiftedRegister< 4, 1>,
    &ARM::Thumb_MoveShiftedRegister< 5, 1>,
    &ARM::Thumb_MoveShiftedRegister< 6, 1>,
    &ARM::Thumb_MoveShiftedRegister< 7, 1>,
    &ARM::Thumb_MoveShiftedRegister< 8, 1>,
    &ARM::Thumb_MoveShiftedRegister< 9, 1>,
    &ARM::Thumb_MoveShiftedRegister<10, 1>,
    &ARM::Thumb_MoveShiftedRegister<11, 1>,
    &ARM::Thumb_MoveShiftedRegister<12, 1>,
    &ARM::Thumb_MoveShiftedRegister<13, 1>,
    &ARM::Thumb_MoveShiftedRegister<14, 1>,
    &ARM::Thumb_MoveShiftedRegister<15, 1>,
    &ARM::Thumb_MoveShiftedRegister<16, 1>,
    &ARM::Thumb_MoveShiftedRegister<17, 1>,
    &ARM::Thumb_MoveShiftedRegister<18, 1>,
    &ARM::Thumb_MoveShiftedRegister<19, 1>,
    &ARM::Thumb_MoveShiftedRegister<20, 1>,
    &ARM::Thumb_MoveShiftedRegister<21, 1>,
    &ARM::Thumb_MoveShiftedRegister<22, 1>,
    &ARM::Thumb_MoveShiftedRegister<23, 1>,
    &ARM::Thumb_MoveShiftedRegister<24, 1>,
    &ARM::Thumb_MoveShiftedRegister<25, 1>,
    &ARM::Thumb_MoveShiftedRegister<26, 1>,
    &ARM::Thumb_MoveShiftedRegister<27, 1>,
    &ARM::Thumb_MoveShiftedRegister<28, 1>,
    &ARM::Thumb_MoveShiftedRegister<29, 1>,
    &ARM::Thumb_MoveShiftedRegister<30, 1>,
    &ARM::Thumb_MoveShiftedRegister<31, 1>,
    &ARM::Thumb_MoveShiftedRegister< 0, 2>,
    &ARM::Thumb_MoveShiftedRegister< 1, 2>,
    &ARM::Thumb_MoveShiftedRegister< 2, 2>,
    &ARM::Thumb_MoveShiftedRegister< 3, 2>,
    &ARM::Thumb_MoveShiftedRegister< 4, 2>,
    &ARM::Thumb_MoveShiftedRegister< 5, 2>,
    &ARM::Thumb_MoveShiftedRegister< 6, 2>,
    &ARM::Thumb_MoveShiftedRegister< 7, 2>,
    &ARM::Thumb_MoveShiftedRegister< 8, 2>,
    &ARM::Thumb_MoveShiftedRegister< 9, 2>,
    &ARM::Thumb_MoveShiftedRegister<10, 2>,
    &ARM::Thumb_MoveShiftedRegister<11, 2>,
    &ARM::Thumb_MoveShiftedRegister<12, 2>,
    &ARM::Thumb_MoveShiftedRegister<13, 2>,
    &ARM::Thumb_MoveShiftedRegister<14, 2>,
    &ARM::Thumb_MoveShiftedRegister<15, 2>,
    &ARM::Thumb_MoveShiftedRegister<16, 2>,
    &ARM::Thumb_MoveShiftedRegister<17, 2>,
    &ARM::Thumb_MoveShiftedRegister<18, 2>,
    &ARM::Thumb_MoveShiftedRegister<19, 2>,
    &ARM::Thumb_MoveShiftedRegister<20, 2>,
    &ARM::Thumb_MoveShiftedRegister<21, 2>,
    &ARM::Thumb_MoveShiftedRegister<22, 2>,
    &ARM::Thumb_MoveShiftedRegister<23, 2>,
    &ARM::Thumb_MoveShiftedRegister<24, 2>,
    &ARM::Thumb_MoveShiftedRegister<25, 2>,
    &ARM::Thumb_MoveShiftedRegister<26, 2>,
    &ARM::Thumb_MoveShiftedRegister<27, 2>,
    &ARM::Thumb_MoveShiftedRegister<28, 2>,
    &ARM::Thumb_MoveShiftedRegister<29, 2>,
    &ARM::Thumb_MoveShiftedRegister<30, 2>,
    &ARM::Thumb_MoveShiftedRegister<31, 2>,
    &ARM::Thumb_AddSubtract<0, 0>,
    &ARM::Thumb_AddSubtract<1, 0>,
    &ARM::Thumb_AddSubtract<2, 0>,
    &ARM::Thumb_AddSubtract<3, 0>,
    &ARM::Thumb_AddSubtract<4, 0>,
    &ARM::Thumb_AddSubtract<5, 0>,
    &ARM::Thumb_AddSubtract<6, 0>,
    &ARM::Thumb_AddSubtract<7, 0>,
    &ARM::Thumb_AddSubtract<0, 1>,
    &ARM::Thumb_AddSubtract<1, 1>,
    &ARM::Thumb_AddSubtract<2, 1>,
    &ARM::Thumb_AddSubtract<3, 1>,
    &ARM::Thumb_AddSubtract<4, 1>,
    &ARM::Thumb_AddSubtract<5, 1>,
    &ARM::Thumb_AddSubtract<6, 1>,
    &ARM::Thumb_AddSubtract<7, 1>,
    &ARM::Thumb_AddSubtract<0, 2>,
    &ARM::Thumb_AddSubtract<1, 2>,
    &ARM::Thumb_AddSubtract<2, 2>,
    &ARM::Thumb_AddSubtract<3, 2>,
    &ARM::Thumb_AddSubtract<4, 2>,
    &ARM::Thumb_AddSubtract<5, 2>,
    &ARM::Thumb_AddSubtract<6, 2>,
    &ARM::Thumb_AddSubtract<7, 2>,
    &ARM::Thumb_AddSubtract<0, 3>,
    &ARM::Thumb_AddSubtract<1, 3>,
    &ARM::Thumb_AddSubtract<2, 3>,
    &ARM::Thumb_AddSubtract<3, 3>,
    &ARM::Thumb_AddSubtract<4, 3>,
    &ARM::Thumb_AddSubtract<5, 3>,
    &ARM::Thumb_AddSubtract<6, 3>,
    &ARM::Thumb_AddSubtract<7, 3>,
    &ARM::Thumb_ImmediateOperations<0, 0>,
    &ARM::Thumb_ImmediateOperations<0, 0>,
    &ARM::Thumb_ImmediateOperations<0, 0>,
    &ARM::Thumb_ImmediateOperations<0, 0>,
    &ARM::Thumb_ImmediateOperations<1, 0>,
    &ARM::Thumb_ImmediateOperations<1, 0>,
    &ARM::Thumb_ImmediateOperations<1, 0>,
    &ARM::Thumb_ImmediateOperations<1, 0>,
    &ARM::Thumb_ImmediateOperations<2, 0>,
    &ARM::Thumb_ImmediateOperations<2, 0>,
    &ARM::Thumb_ImmediateOperations<2, 0>,
    &ARM::Thumb_ImmediateOperations<2, 0>,
    &ARM::Thumb_ImmediateOperations<3, 0>,
    &ARM::Thumb_ImmediateOperations<3, 0>,
    &ARM::Thumb_ImmediateOperations<3, 0>,
    &ARM::Thumb_ImmediateOperations<3, 0>,
    &ARM::Thumb_ImmediateOperations<4, 0>,
    &ARM::Thumb_ImmediateOperations<4, 0>,
    &ARM::Thumb_ImmediateOperations<4, 0>,
    &ARM::Thumb_ImmediateOperations<4, 0>,
    &ARM::Thumb_ImmediateOperations<5, 0>,
    &ARM::Thumb_ImmediateOperations<5, 0>,
    &ARM::Thumb_ImmediateOperations<5, 0>,
    &ARM::Thumb_ImmediateOperations<5, 0>,
    &ARM::Thumb_ImmediateOperations<6, 0>,
    &ARM::Thumb_ImmediateOperations<6, 0>,
    &ARM::Thumb_ImmediateOperations<6, 0>,
    &ARM::Thumb_ImmediateOperations<6, 0>,
    &ARM::Thumb_ImmediateOperations<7, 0>,
    &ARM::Thumb_ImmediateOperations<7, 0>,
    &ARM::Thumb_ImmediateOperations<7, 0>,
    &ARM::Thumb_ImmediateOperations<7, 0>,
    &ARM::Thumb_ImmediateOperations<0, 1>,
    &ARM::Thumb_ImmediateOperations<0, 1>,
    &ARM::Thumb_ImmediateOperations<0, 1>,
    &ARM::Thumb_ImmediateOperations<0, 1>,
    &ARM::Thumb_ImmediateOperations<1, 1>,
    &ARM::Thumb_ImmediateOperations<1, 1>,
    &ARM::Thumb_ImmediateOperations<1, 1>,
    &ARM::Thumb_ImmediateOperations<1, 1>,
    &ARM::Thumb_ImmediateOperations<2, 1>,
    &ARM::Thumb_ImmediateOperations<2, 1>,
    &ARM::Thumb_ImmediateOperations<2, 1>,
    &ARM::Thumb_ImmediateOperations<2, 1>,
    &ARM::Thumb_ImmediateOperations<3, 1>,
    &ARM::Thumb_ImmediateOperations<3, 1>,
    &ARM::Thumb_ImmediateOperations<3, 1>,
    &ARM::Thumb_ImmediateOperations<3, 1>,
    &ARM::Thumb_ImmediateOperations<4, 1>,
    &ARM::Thumb_ImmediateOperations<4, 1>,
    &ARM::Thumb_ImmediateOperations<4, 1>,
    &ARM::Thumb_ImmediateOperations<4, 1>,
    &ARM::Thumb_ImmediateOperations<5, 1>,
    &ARM::Thumb_ImmediateOperations<5, 1>,
    &ARM::Thumb_ImmediateOperations<5, 1>,
    &ARM::Thumb_ImmediateOperations<5, 1>,
    &ARM::Thumb_ImmediateOperations<6, 1>,
    &ARM::Thumb_ImmediateOperations<6, 1>,
    &ARM::Thumb_ImmediateOperations<6, 1>,
    &ARM::Thumb_ImmediateOperations<6, 1>,
    &ARM::Thumb_ImmediateOperations<7, 1>,
    &ARM::Thumb_ImmediateOperations<7, 1>,
    &ARM::Thumb_ImmediateOperations<7, 1>,
    &ARM::Thumb_ImmediateOperations<7, 1>,
    &ARM::Thumb_ImmediateOperations<0, 2>,
    &ARM::Thumb_ImmediateOperations<0, 2>,
    &ARM::Thumb_ImmediateOperations<0, 2>,
    &ARM::Thumb_ImmediateOperations<0, 2>,
    &ARM::Thumb_ImmediateOperations<1, 2>,
    &ARM::Thumb_ImmediateOperations<1, 2>,
    &ARM::Thumb_ImmediateOperations<1, 2>,
    &ARM::Thumb_ImmediateOperations<1, 2>,
    &ARM::Thumb_ImmediateOperations<2, 2>,
    &ARM::Thumb_ImmediateOperations<2, 2>,
    &ARM::Thumb_ImmediateOperations<2, 2>,
    &ARM::Thumb_ImmediateOperations<2, 2>,
    &ARM::Thumb_ImmediateOperations<3, 2>,
    &ARM::Thumb_ImmediateOperations<3, 2>,
    &ARM::Thumb_ImmediateOperations<3, 2>,
    &ARM::Thumb_ImmediateOperations<3, 2>,
    &ARM::Thumb_ImmediateOperations<4, 2>,
    &ARM::Thumb_ImmediateOperations<4, 2>,
    &ARM::Thumb_ImmediateOperations<4, 2>,
    &ARM::Thumb_ImmediateOperations<4, 2>,
    &ARM::Thumb_ImmediateOperations<5, 2>,
    &ARM::Thumb_ImmediateOperations<5, 2>,
    &ARM::Thumb_ImmediateOperations<5, 2>,
    &ARM::Thumb_ImmediateOperations<5, 2>,
    &ARM::Thumb_ImmediateOperations<6, 2>,
    &ARM::Thumb_ImmediateOperations<6, 2>,
    &ARM::Thumb_ImmediateOperations<6, 2>,
    &ARM::Thumb_ImmediateOperations<6, 2>,
    &ARM::Thumb_ImmediateOperations<7, 2>,
    &ARM::Thumb_ImmediateOperations<7, 2>,
    &ARM::Thumb_ImmediateOperations<7, 2>,
    &ARM::Thumb_ImmediateOperations<7, 2>,
    &ARM::Thumb_ImmediateOperations<0, 3>,
    &ARM::Thumb_ImmediateOperations<0, 3>,
    &ARM::Thumb_ImmediateOperations<0, 3>,
    &ARM::Thumb_ImmediateOperations<0, 3>,
    &ARM::Thumb_ImmediateOperations<1, 3>,
    &ARM::Thumb_ImmediateOperations<1, 3>,
    &ARM::Thumb_ImmediateOperations<1, 3>,
    &ARM::Thumb_ImmediateOperations<1, 3>,
    &ARM::Thumb_ImmediateOperations<2, 3>,
    &ARM::Thumb_ImmediateOperations<2, 3>,
    &ARM::Thumb_ImmediateOperations<2, 3>,
    &ARM::Thumb_ImmediateOperations<2, 3>,
    &ARM::Thumb_ImmediateOperations<3, 3>,
    &ARM::Thumb_ImmediateOperations<3, 3>,
    &ARM::Thumb_ImmediateOperations<3, 3>,
    &ARM::Thumb_ImmediateOperations<3, 3>,
    &ARM::Thumb_ImmediateOperations<4, 3>,
    &ARM::Thumb_ImmediateOperations<4, 3>,
    &ARM::Thumb_ImmediateOperations<4, 3>,
    &ARM::Thumb_ImmediateOperations<4, 3>,
    &ARM::Thumb_ImmediateOperations<5, 3>,
    &ARM::Thumb_ImmediateOperations<5, 3>,
    &ARM::Thumb_ImmediateOperations<5, 3>,
    &ARM::Thumb_ImmediateOperations<5, 3>,
    &ARM::Thumb_ImmediateOperations<6, 3>,
    &ARM::Thumb_ImmediateOperations<6, 3>,
    &ARM::Thumb_ImmediateOperations<6, 3>,
    &ARM::Thumb_ImmediateOperations<6, 3>,
    &ARM::Thumb_ImmediateOperations<7, 3>,
    &ARM::Thumb_ImmediateOperations<7, 3>,
    &ARM::Thumb_ImmediateOperations<7, 3>,
    &ARM::Thumb_ImmediateOperations<7, 3>,
    &ARM::Thumb_ALUOperations< 0>,
    &ARM::Thumb_ALUOperations< 1>,
    &ARM::Thumb_ALUOperations< 2>,
    &ARM::Thumb_ALUOperations< 3>,
    &ARM::Thumb_ALUOperations< 4>,
    &ARM::Thumb_ALUOperations< 5>,
    &ARM::Thumb_ALUOperations< 6>,
    &ARM::Thumb_ALUOperations< 7>,
    &ARM::Thumb_ALUOperations< 8>,
    &ARM::Thumb_ALUOperations< 9>,
    &ARM::Thumb_ALUOperations<10>,
    &ARM::Thumb_ALUOperations<11>,
    &ARM::Thumb_ALUOperations<12>,
    &ARM::Thumb_ALUOperations<13>,
    &ARM::Thumb_ALUOperations<14>,
    &ARM::Thumb_ALUOperations<15>,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_HighRegisterOperations<1, 0, 0>,
    &ARM::Thumb_HighRegisterOperations<0, 1, 0>,
    &ARM::Thumb_HighRegisterOperations<1, 1, 0>,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_HighRegisterOperations<1, 0, 1>,
    &ARM::Thumb_HighRegisterOperations<0, 1, 1>,
    &ARM::Thumb_HighRegisterOperations<1, 1, 1>,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_HighRegisterOperations<1, 0, 2>,
    &ARM::Thumb_HighRegisterOperations<0, 1, 2>,
    &ARM::Thumb_HighRegisterOperations<1, 1, 2>,
    &ARM::Thumb_HighRegisterOperations<0, 0, 3>,
    &ARM::Thumb_HighRegisterOperations<1, 0, 3>,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_LoadPCRelative<0>,
    &ARM::Thumb_LoadPCRelative<0>,
    &ARM::Thumb_LoadPCRelative<0>,
    &ARM::Thumb_LoadPCRelative<0>,
    &ARM::Thumb_LoadPCRelative<1>,
    &ARM::Thumb_LoadPCRelative<1>,
    &ARM::Thumb_LoadPCRelative<1>,
    &ARM::Thumb_LoadPCRelative<1>,
    &ARM::Thumb_LoadPCRelative<2>,
    &ARM::Thumb_LoadPCRelative<2>,
    &ARM::Thumb_LoadPCRelative<2>,
    &ARM::Thumb_LoadPCRelative<2>,
    &ARM::Thumb_LoadPCRelative<3>,
    &ARM::Thumb_LoadPCRelative<3>,
    &ARM::Thumb_LoadPCRelative<3>,
    &ARM::Thumb_LoadPCRelative<3>,
    &ARM::Thumb_LoadPCRelative<4>,
    &ARM::Thumb_LoadPCRelative<4>,
    &ARM::Thumb_LoadPCRelative<4>,
    &ARM::Thumb_LoadPCRelative<4>,
    &ARM::Thumb_LoadPCRelative<5>,
    &ARM::Thumb_LoadPCRelative<5>,
    &ARM::Thumb_LoadPCRelative<5>,
    &ARM::Thumb_LoadPCRelative<5>,
    &ARM::Thumb_LoadPCRelative<6>,
    &ARM::Thumb_LoadPCRelative<6>,
    &ARM::Thumb_LoadPCRelative<6>,
    &ARM::Thumb_LoadPCRelative<6>,
    &ARM::Thumb_LoadPCRelative<7>,
    &ARM::Thumb_LoadPCRelative<7>,
    &ARM::Thumb_LoadPCRelative<7>,
    &ARM::Thumb_LoadPCRelative<7>,
    &ARM::Thumb_LoadStoreRegisterOffset<0, 0>,
    &ARM::Thumb_LoadStoreRegisterOffset<1, 0>,
    &ARM::Thumb_LoadStoreRegisterOffset<2, 0>,
    &ARM::Thumb_LoadStoreRegisterOffset<3, 0>,
    &ARM::Thumb_LoadStoreRegisterOffset<4, 0>,
    &ARM::Thumb_LoadStoreRegisterOffset<5, 0>,
    &ARM::Thumb_LoadStoreRegisterOffset<6, 0>,
    &ARM::Thumb_LoadStoreRegisterOffset<7, 0>,
    &ARM::Thumb_LoadStoreByteHalf<0, 0>,
    &ARM::Thumb_LoadStoreByteHalf<1, 0>,
    &ARM::Thumb_LoadStoreByteHalf<2, 0>,
    &ARM::Thumb_LoadStoreByteHalf<3, 0>,
    &ARM::Thumb_LoadStoreByteHalf<4, 0>,
    &ARM::Thumb_LoadStoreByteHalf<5, 0>,
    &ARM::Thumb_LoadStoreByteHalf<6, 0>,
    &ARM::Thumb_LoadStoreByteHalf<7, 0>,
    &ARM::Thumb_LoadStoreRegisterOffset<0, 1>,
    &ARM::Thumb_LoadStoreRegisterOffset<1, 1>,
    &ARM::Thumb_LoadStoreRegisterOffset<2, 1>,
    &ARM::Thumb_LoadStoreRegisterOffset<3, 1>,
    &ARM::Thumb_LoadStoreRegisterOffset<4, 1>,
    &ARM::Thumb_LoadStoreRegisterOffset<5, 1>,
    &ARM::Thumb_LoadStoreRegisterOffset<6, 1>,
    &ARM::Thumb_LoadStoreRegisterOffset<7, 1>,
    &ARM::Thumb_LoadStoreByteHalf<0, 1>,
    &ARM::Thumb_LoadStoreByteHalf<1, 1>,
    &ARM::Thumb_LoadStoreByteHalf<2, 1>,
    &ARM::Thumb_LoadStoreByteHalf<3, 1>,
    &ARM::Thumb_LoadStoreByteHalf<4, 1>,
    &ARM::Thumb_LoadStoreByteHalf<5, 1>,
    &ARM::Thumb_LoadStoreByteHalf<6, 1>,
    &ARM::Thumb_LoadStoreByteHalf<7, 1>,
    &ARM::Thumb_LoadStoreRegisterOffset<0, 2>,
    &ARM::Thumb_LoadStoreRegisterOffset<1, 2>,
    &ARM::Thumb_LoadStoreRegisterOffset<2, 2>,
    &ARM::Thumb_LoadStoreRegisterOffset<3, 2>,
    &ARM::Thumb_LoadStoreRegisterOffset<4, 2>,
    &ARM::Thumb_LoadStoreRegisterOffset<5, 2>,
    &ARM::Thumb_LoadStoreRegisterOffset<6, 2>,
    &ARM::Thumb_LoadStoreRegisterOffset<7, 2>,
    &ARM::Thumb_LoadStoreByteHalf<0, 2>,
    &ARM::Thumb_LoadStoreByteHalf<1, 2>,
    &ARM::Thumb_LoadStoreByteHalf<2, 2>,
    &ARM::Thumb_LoadStoreByteHalf<3, 2>,
    &ARM::Thumb_LoadStoreByteHalf<4, 2>,
    &ARM::Thumb_LoadStoreByteHalf<5, 2>,
    &ARM::Thumb_LoadStoreByteHalf<6, 2>,
    &ARM::Thumb_LoadStoreByteHalf<7, 2>,
    &ARM::Thumb_LoadStoreRegisterOffset<0, 3>,
    &ARM::Thumb_LoadStoreRegisterOffset<1, 3>,
    &ARM::Thumb_LoadStoreRegisterOffset<2, 3>,
    &ARM::Thumb_LoadStoreRegisterOffset<3, 3>,
    &ARM::Thumb_LoadStoreRegisterOffset<4, 3>,
    &ARM::Thumb_LoadStoreRegisterOffset<5, 3>,
    &ARM::Thumb_LoadStoreRegisterOffset<6, 3>,
    &ARM::Thumb_LoadStoreRegisterOffset<7, 3>,
    &ARM::Thumb_LoadStoreByteHalf<0, 3>,
    &ARM::Thumb_LoadStoreByteHalf<1, 3>,
    &ARM::Thumb_LoadStoreByteHalf<2, 3>,
    &ARM::Thumb_LoadStoreByteHalf<3, 3>,
    &ARM::Thumb_LoadStoreByteHalf<4, 3>,
    &ARM::Thumb_LoadStoreByteHalf<5, 3>,
    &ARM::Thumb_LoadStoreByteHalf<6, 3>,
    &ARM::Thumb_LoadStoreByteHalf<7, 3>,
    &ARM::Thumb_LoadStoreImmediateOffset< 0, 0>,
    &ARM::Thumb_LoadStoreImmediateOffset< 1, 0>,
    &ARM::Thumb_LoadStoreImmediateOffset< 2, 0>,
    &ARM::Thumb_LoadStoreImmediateOffset< 3, 0>,
    &ARM::Thumb_LoadStoreImmediateOffset< 4, 0>,
    &ARM::Thumb_LoadStoreImmediateOffset< 5, 0>,
    &ARM::Thumb_LoadStoreImmediateOffset< 6, 0>,
    &ARM::Thumb_LoadStoreImmediateOffset< 7, 0>,
    &ARM::Thumb_LoadStoreImmediateOffset< 8, 0>,
    &ARM::Thumb_LoadStoreImmediateOffset< 9, 0>,
    &ARM::Thumb_LoadStoreImmediateOffset<10, 0>,
    &ARM::Thumb_LoadStoreImmediateOffset<11, 0>,
    &ARM::Thumb_LoadStoreImmediateOffset<12, 0>,
    &ARM::Thumb_LoadStoreImmediateOffset<13, 0>,
    &ARM::Thumb_LoadStoreImmediateOffset<14, 0>,
    &ARM::Thumb_LoadStoreImmediateOffset<15, 0>,
    &ARM::Thumb_LoadStoreImmediateOffset<16, 0>,
    &ARM::Thumb_LoadStoreImmediateOffset<17, 0>,
    &ARM::Thumb_LoadStoreImmediateOffset<18, 0>,
    &ARM::Thumb_LoadStoreImmediateOffset<19, 0>,
    &ARM::Thumb_LoadStoreImmediateOffset<20, 0>,
    &ARM::Thumb_LoadStoreImmediateOffset<21, 0>,
    &ARM::Thumb_LoadStoreImmediateOffset<22, 0>,
    &ARM::Thumb_LoadStoreImmediateOffset<23, 0>,
    &ARM::Thumb_LoadStoreImmediateOffset<24, 0>,
    &ARM::Thumb_LoadStoreImmediateOffset<25, 0>,
    &ARM::Thumb_LoadStoreImmediateOffset<26, 0>,
    &ARM::Thumb_LoadStoreImmediateOffset<27, 0>,
    &ARM::Thumb_LoadStoreImmediateOffset<28, 0>,
    &ARM::Thumb_LoadStoreImmediateOffset<29, 0>,
    &ARM::Thumb_LoadStoreImmediateOffset<30, 0>,
    &ARM::Thumb_LoadStoreImmediateOffset<31, 0>,
    &ARM::Thumb_LoadStoreImmediateOffset< 0, 1>,
    &ARM::Thumb_LoadStoreImmediateOffset< 1, 1>,
    &ARM::Thumb_LoadStoreImmediateOffset< 2, 1>,
    &ARM::Thumb_LoadStoreImmediateOffset< 3, 1>,
    &ARM::Thumb_LoadStoreImmediateOffset< 4, 1>,
    &ARM::Thumb_LoadStoreImmediateOffset< 5, 1>,
    &ARM::Thumb_LoadStoreImmediateOffset< 6, 1>,
    &ARM::Thumb_LoadStoreImmediateOffset< 7, 1>,
    &ARM::Thumb_LoadStoreImmediateOffset< 8, 1>,
    &ARM::Thumb_LoadStoreImmediateOffset< 9, 1>,
    &ARM::Thumb_LoadStoreImmediateOffset<10, 1>,
    &ARM::Thumb_LoadStoreImmediateOffset<11, 1>,
    &ARM::Thumb_LoadStoreImmediateOffset<12, 1>,
    &ARM::Thumb_LoadStoreImmediateOffset<13, 1>,
    &ARM::Thumb_LoadStoreImmediateOffset<14, 1>,
    &ARM::Thumb_LoadStoreImmediateOffset<15, 1>,
    &ARM::Thumb_LoadStoreImmediateOffset<16, 1>,
    &ARM::Thumb_LoadStoreImmediateOffset<17, 1>,
    &ARM::Thumb_LoadStoreImmediateOffset<18, 1>,
    &ARM::Thumb_LoadStoreImmediateOffset<19, 1>,
    &ARM::Thumb_LoadStoreImmediateOffset<20, 1>,
    &ARM::Thumb_LoadStoreImmediateOffset<21, 1>,
    &ARM::Thumb_LoadStoreImmediateOffset<22, 1>,
    &ARM::Thumb_LoadStoreImmediateOffset<23, 1>,
    &ARM::Thumb_LoadStoreImmediateOffset<24, 1>,
    &ARM::Thumb_LoadStoreImmediateOffset<25, 1>,
    &ARM::Thumb_LoadStoreImmediateOffset<26, 1>,
    &ARM::Thumb_LoadStoreImmediateOffset<27, 1>,
    &ARM::Thumb_LoadStoreImmediateOffset<28, 1>,
    &ARM::Thumb_LoadStoreImmediateOffset<29, 1>,
    &ARM::Thumb_LoadStoreImmediateOffset<30, 1>,
    &ARM::Thumb_LoadStoreImmediateOffset<31, 1>,
    &ARM::Thumb_LoadStoreImmediateOffset< 0, 2>,
    &ARM::Thumb_LoadStoreImmediateOffset< 1, 2>,
    &ARM::Thumb_LoadStoreImmediateOffset< 2, 2>,
    &ARM::Thumb_LoadStoreImmediateOffset< 3, 2>,
    &ARM::Thumb_LoadStoreImmediateOffset< 4, 2>,
    &ARM::Thumb_LoadStoreImmediateOffset< 5, 2>,
    &ARM::Thumb_LoadStoreImmediateOffset< 6, 2>,
    &ARM::Thumb_LoadStoreImmediateOffset< 7, 2>,
    &ARM::Thumb_LoadStoreImmediateOffset< 8, 2>,
    &ARM::Thumb_LoadStoreImmediateOffset< 9, 2>,
    &ARM::Thumb_LoadStoreImmediateOffset<10, 2>,
    &ARM::Thumb_LoadStoreImmediateOffset<11, 2>,
    &ARM::Thumb_LoadStoreImmediateOffset<12, 2>,
    &ARM::Thumb_LoadStoreImmediateOffset<13, 2>,
    &ARM::Thumb_LoadStoreImmediateOffset<14, 2>,
    &ARM::Thumb_LoadStoreImmediateOffset<15, 2>,
    &ARM::Thumb_LoadStoreImmediateOffset<16, 2>,
    &ARM::Thumb_LoadStoreImmediateOffset<17, 2>,
    &ARM::Thumb_LoadStoreImmediateOffset<18, 2>,
    &ARM::Thumb_LoadStoreImmediateOffset<19, 2>,
    &ARM::Thumb_LoadStoreImmediateOffset<20, 2>,
    &ARM::Thumb_LoadStoreImmediateOffset<21, 2>,
    &ARM::Thumb_LoadStoreImmediateOffset<22, 2>,
    &ARM::Thumb_LoadStoreImmediateOffset<23, 2>,
    &ARM::Thumb_LoadStoreImmediateOffset<24, 2>,
    &ARM::Thumb_LoadStoreImmediateOffset<25, 2>,
    &ARM::Thumb_LoadStoreImmediateOffset<26, 2>,
    &ARM::Thumb_LoadStoreImmediateOffset<27, 2>,
    &ARM::Thumb_LoadStoreImmediateOffset<28, 2>,
    &ARM::Thumb_LoadStoreImmediateOffset<29, 2>,
    &ARM::Thumb_LoadStoreImmediateOffset<30, 2>,
    &ARM::Thumb_LoadStoreImmediateOffset<31, 2>,
    &ARM::Thumb_LoadStoreImmediateOffset< 0, 3>,
    &ARM::Thumb_LoadStoreImmediateOffset< 1, 3>,
    &ARM::Thumb_LoadStoreImmediateOffset< 2, 3>,
    &ARM::Thumb_LoadStoreImmediateOffset< 3, 3>,
    &ARM::Thumb_LoadStoreImmediateOffset< 4, 3>,
    &ARM::Thumb_LoadStoreImmediateOffset< 5, 3>,
    &ARM::Thumb_LoadStoreImmediateOffset< 6, 3>,
    &ARM::Thumb_LoadStoreImmediateOffset< 7, 3>,
    &ARM::Thumb_LoadStoreImmediateOffset< 8, 3>,
    &ARM::Thumb_LoadStoreImmediateOffset< 9, 3>,
    &ARM::Thumb_LoadStoreImmediateOffset<10, 3>,
    &ARM::Thumb_LoadStoreImmediateOffset<11, 3>,
    &ARM::Thumb_LoadStoreImmediateOffset<12, 3>,
    &ARM::Thumb_LoadStoreImmediateOffset<13, 3>,
    &ARM::Thumb_LoadStoreImmediateOffset<14, 3>,
    &ARM::Thumb_LoadStoreImmediateOffset<15, 3>,
    &ARM::Thumb_LoadStoreImmediateOffset<16, 3>,
    &ARM::Thumb_LoadStoreImmediateOffset<17, 3>,
    &ARM::Thumb_LoadStoreImmediateOffset<18, 3>,
    &ARM::Thumb_LoadStoreImmediateOffset<19, 3>,
    &ARM::Thumb_LoadStoreImmediateOffset<20, 3>,
    &ARM::Thumb_LoadStoreImmediateOffset<21, 3>,
    &ARM::Thumb_LoadStoreImmediateOffset<22, 3>,
    &ARM::Thumb_LoadStoreImmediateOffset<23, 3>,
    &ARM::Thumb_LoadStoreImmediateOffset<24, 3>,
    &ARM::Thumb_LoadStoreImmediateOffset<25, 3>,
    &ARM::Thumb_LoadStoreImmediateOffset<26, 3>,
    &ARM::Thumb_LoadStoreImmediateOffset<27, 3>,
    &ARM::Thumb_LoadStoreImmediateOffset<28, 3>,
    &ARM::Thumb_LoadStoreImmediateOffset<29, 3>,
    &ARM::Thumb_LoadStoreImmediateOffset<30, 3>,
    &ARM::Thumb_LoadStoreImmediateOffset<31, 3>,
    &ARM::Thumb_LoadStoreHalf< 0, 0>,
    &ARM::Thumb_LoadStoreHalf< 1, 0>,
    &ARM::Thumb_LoadStoreHalf< 2, 0>,
    &ARM::Thumb_LoadStoreHalf< 3, 0>,
    &ARM::Thumb_LoadStoreHalf< 4, 0>,
    &ARM::Thumb_LoadStoreHalf< 5, 0>,
    &ARM::Thumb_LoadStoreHalf< 6, 0>,
    &ARM::Thumb_LoadStoreHalf< 7, 0>,
    &ARM::Thumb_LoadStoreHalf< 8, 0>,
    &ARM::Thumb_LoadStoreHalf< 9, 0>,
    &ARM::Thumb_LoadStoreHalf<10, 0>,
    &ARM::Thumb_LoadStoreHalf<11, 0>,
    &ARM::Thumb_LoadStoreHalf<12, 0>,
    &ARM::Thumb_LoadStoreHalf<13, 0>,
    &ARM::Thumb_LoadStoreHalf<14, 0>,
    &ARM::Thumb_LoadStoreHalf<15, 0>,
    &ARM::Thumb_LoadStoreHalf<16, 0>,
    &ARM::Thumb_LoadStoreHalf<17, 0>,
    &ARM::Thumb_LoadStoreHalf<18, 0>,
    &ARM::Thumb_LoadStoreHalf<19, 0>,
    &ARM::Thumb_LoadStoreHalf<20, 0>,
    &ARM::Thumb_LoadStoreHalf<21, 0>,
    &ARM::Thumb_LoadStoreHalf<22, 0>,
    &ARM::Thumb_LoadStoreHalf<23, 0>,
    &ARM::Thumb_LoadStoreHalf<24, 0>,
    &ARM::Thumb_LoadStoreHalf<25, 0>,
    &ARM::Thumb_LoadStoreHalf<26, 0>,
    &ARM::Thumb_LoadStoreHalf<27, 0>,
    &ARM::Thumb_LoadStoreHalf<28, 0>,
    &ARM::Thumb_LoadStoreHalf<29, 0>,
    &ARM::Thumb_LoadStoreHalf<30, 0>,
    &ARM::Thumb_LoadStoreHalf<31, 0>,
    &ARM::Thumb_LoadStoreHalf< 0, 1>,
    &ARM::Thumb_LoadStoreHalf< 1, 1>,
    &ARM::Thumb_LoadStoreHalf< 2, 1>,
    &ARM::Thumb_LoadStoreHalf< 3, 1>,
    &ARM::Thumb_LoadStoreHalf< 4, 1>,
    &ARM::Thumb_LoadStoreHalf< 5, 1>,
    &ARM::Thumb_LoadStoreHalf< 6, 1>,
    &ARM::Thumb_LoadStoreHalf< 7, 1>,
    &ARM::Thumb_LoadStoreHalf< 8, 1>,
    &ARM::Thumb_LoadStoreHalf< 9, 1>,
    &ARM::Thumb_LoadStoreHalf<10, 1>,
    &ARM::Thumb_LoadStoreHalf<11, 1>,
    &ARM::Thumb_LoadStoreHalf<12, 1>,
    &ARM::Thumb_LoadStoreHalf<13, 1>,
    &ARM::Thumb_LoadStoreHalf<14, 1>,
    &ARM::Thumb_LoadStoreHalf<15, 1>,
    &ARM::Thumb_LoadStoreHalf<16, 1>,
    &ARM::Thumb_LoadStoreHalf<17, 1>,
    &ARM::Thumb_LoadStoreHalf<18, 1>,
    &ARM::Thumb_LoadStoreHalf<19, 1>,
    &ARM::Thumb_LoadStoreHalf<20, 1>,
    &ARM::Thumb_LoadStoreHalf<21, 1>,
    &ARM::Thumb_LoadStoreHalf<22, 1>,
    &ARM::Thumb_LoadStoreHalf<23, 1>,
    &ARM::Thumb_LoadStoreHalf<24, 1>,
    &ARM::Thumb_LoadStoreHalf<25, 1>,
    &ARM::Thumb_LoadStoreHalf<26, 1>,
    &ARM::Thumb_LoadStoreHalf<27, 1>,
    &ARM::Thumb_LoadStoreHalf<28, 1>,
    &ARM::Thumb_LoadStoreHalf<29, 1>,
    &ARM::Thumb_LoadStoreHalf<30, 1>,
    &ARM::Thumb_LoadStoreHalf<31, 1>,
    &ARM::Thumb_LoadStoreSPRelative<0, 0>,
    &ARM::Thumb_LoadStoreSPRelative<0, 0>,
    &ARM::Thumb_LoadStoreSPRelative<0, 0>,
    &ARM::Thumb_LoadStoreSPRelative<0, 0>,
    &ARM::Thumb_LoadStoreSPRelative<1, 0>,
    &ARM::Thumb_LoadStoreSPRelative<1, 0>,
    &ARM::Thumb_LoadStoreSPRelative<1, 0>,
    &ARM::Thumb_LoadStoreSPRelative<1, 0>,
    &ARM::Thumb_LoadStoreSPRelative<2, 0>,
    &ARM::Thumb_LoadStoreSPRelative<2, 0>,
    &ARM::Thumb_LoadStoreSPRelative<2, 0>,
    &ARM::Thumb_LoadStoreSPRelative<2, 0>,
    &ARM::Thumb_LoadStoreSPRelative<3, 0>,
    &ARM::Thumb_LoadStoreSPRelative<3, 0>,
    &ARM::Thumb_LoadStoreSPRelative<3, 0>,
    &ARM::Thumb_LoadStoreSPRelative<3, 0>,
    &ARM::Thumb_LoadStoreSPRelative<4, 0>,
    &ARM::Thumb_LoadStoreSPRelative<4, 0>,
    &ARM::Thumb_LoadStoreSPRelative<4, 0>,
    &ARM::Thumb_LoadStoreSPRelative<4, 0>,
    &ARM::Thumb_LoadStoreSPRelative<5, 0>,
    &ARM::Thumb_LoadStoreSPRelative<5, 0>,
    &ARM::Thumb_LoadStoreSPRelative<5, 0>,
    &ARM::Thumb_LoadStoreSPRelative<5, 0>,
    &ARM::Thumb_LoadStoreSPRelative<6, 0>,
    &ARM::Thumb_LoadStoreSPRelative<6, 0>,
    &ARM::Thumb_LoadStoreSPRelative<6, 0>,
    &ARM::Thumb_LoadStoreSPRelative<6, 0>,
    &ARM::Thumb_LoadStoreSPRelative<7, 0>,
    &ARM::Thumb_LoadStoreSPRelative<7, 0>,
    &ARM::Thumb_LoadStoreSPRelative<7, 0>,
    &ARM::Thumb_LoadStoreSPRelative<7, 0>,
    &ARM::Thumb_LoadStoreSPRelative<0, 1>,
    &ARM::Thumb_LoadStoreSPRelative<0, 1>,
    &ARM::Thumb_LoadStoreSPRelative<0, 1>,
    &ARM::Thumb_LoadStoreSPRelative<0, 1>,
    &ARM::Thumb_LoadStoreSPRelative<1, 1>,
    &ARM::Thumb_LoadStoreSPRelative<1, 1>,
    &ARM::Thumb_LoadStoreSPRelative<1, 1>,
    &ARM::Thumb_LoadStoreSPRelative<1, 1>,
    &ARM::Thumb_LoadStoreSPRelative<2, 1>,
    &ARM::Thumb_LoadStoreSPRelative<2, 1>,
    &ARM::Thumb_LoadStoreSPRelative<2, 1>,
    &ARM::Thumb_LoadStoreSPRelative<2, 1>,
    &ARM::Thumb_LoadStoreSPRelative<3, 1>,
    &ARM::Thumb_LoadStoreSPRelative<3, 1>,
    &ARM::Thumb_LoadStoreSPRelative<3, 1>,
    &ARM::Thumb_LoadStoreSPRelative<3, 1>,
    &ARM::Thumb_LoadStoreSPRelative<4, 1>,
    &ARM::Thumb_LoadStoreSPRelative<4, 1>,
    &ARM::Thumb_LoadStoreSPRelative<4, 1>,
    &ARM::Thumb_LoadStoreSPRelative<4, 1>,
    &ARM::Thumb_LoadStoreSPRelative<5, 1>,
    &ARM::Thumb_LoadStoreSPRelative<5, 1>,
    &ARM::Thumb_LoadStoreSPRelative<5, 1>,
    &ARM::Thumb_LoadStoreSPRelative<5, 1>,
    &ARM::Thumb_LoadStoreSPRelative<6, 1>,
    &ARM::Thumb_LoadStoreSPRelative<6, 1>,
    &ARM::Thumb_LoadStoreSPRelative<6, 1>,
    &ARM::Thumb_LoadStoreSPRelative<6, 1>,
    &ARM::Thumb_LoadStoreSPRelative<7, 1>,
    &ARM::Thumb_LoadStoreSPRelative<7, 1>,
    &ARM::Thumb_LoadStoreSPRelative<7, 1>,
    &ARM::Thumb_LoadStoreSPRelative<7, 1>,
    &ARM::Thumb_LoadRelativeAddress<0, 0>,
    &ARM::Thumb_LoadRelativeAddress<0, 0>,
    &ARM::Thumb_LoadRelativeAddress<0, 0>,
    &ARM::Thumb_LoadRelativeAddress<0, 0>,
    &ARM::Thumb_LoadRelativeAddress<1, 0>,
    &ARM::Thumb_LoadRelativeAddress<1, 0>,
    &ARM::Thumb_LoadRelativeAddress<1, 0>,
    &ARM::Thumb_LoadRelativeAddress<1, 0>,
    &ARM::Thumb_LoadRelativeAddress<2, 0>,
    &ARM::Thumb_LoadRelativeAddress<2, 0>,
    &ARM::Thumb_LoadRelativeAddress<2, 0>,
    &ARM::Thumb_LoadRelativeAddress<2, 0>,
    &ARM::Thumb_LoadRelativeAddress<3, 0>,
    &ARM::Thumb_LoadRelativeAddress<3, 0>,
    &ARM::Thumb_LoadRelativeAddress<3, 0>,
    &ARM::Thumb_LoadRelativeAddress<3, 0>,
    &ARM::Thumb_LoadRelativeAddress<4, 0>,
    &ARM::Thumb_LoadRelativeAddress<4, 0>,
    &ARM::Thumb_LoadRelativeAddress<4, 0>,
    &ARM::Thumb_LoadRelativeAddress<4, 0>,
    &ARM::Thumb_LoadRelativeAddress<5, 0>,
    &ARM::Thumb_LoadRelativeAddress<5, 0>,
    &ARM::Thumb_LoadRelativeAddress<5, 0>,
    &ARM::Thumb_LoadRelativeAddress<5, 0>,
    &ARM::Thumb_LoadRelativeAddress<6, 0>,
    &ARM::Thumb_LoadRelativeAddress<6, 0>,
    &ARM::Thumb_LoadRelativeAddress<6, 0>,
    &ARM::Thumb_LoadRelativeAddress<6, 0>,
    &ARM::Thumb_LoadRelativeAddress<7, 0>,
    &ARM::Thumb_LoadRelativeAddress<7, 0>,
    &ARM::Thumb_LoadRelativeAddress<7, 0>,
    &ARM::Thumb_LoadRelativeAddress<7, 0>,
    &ARM::Thumb_LoadRelativeAddress<0, 1>,
    &ARM::Thumb_LoadRelativeAddress<0, 1>,
    &ARM::Thumb_LoadRelativeAddress<0, 1>,
    &ARM::Thumb_LoadRelativeAddress<0, 1>,
    &ARM::Thumb_LoadRelativeAddress<1, 1>,
    &ARM::Thumb_LoadRelativeAddress<1, 1>,
    &ARM::Thumb_LoadRelativeAddress<1, 1>,
    &ARM::Thumb_LoadRelativeAddress<1, 1>,
    &ARM::Thumb_LoadRelativeAddress<2, 1>,
    &ARM::Thumb_LoadRelativeAddress<2, 1>,
    &ARM::Thumb_LoadRelativeAddress<2, 1>,
    &ARM::Thumb_LoadRelativeAddress<2, 1>,
    &ARM::Thumb_LoadRelativeAddress<3, 1>,
    &ARM::Thumb_LoadRelativeAddress<3, 1>,
    &ARM::Thumb_LoadRelativeAddress<3, 1>,
    &ARM::Thumb_LoadRelativeAddress<3, 1>,
    &ARM::Thumb_LoadRelativeAddress<4, 1>,
    &ARM::Thumb_LoadRelativeAddress<4, 1>,
    &ARM::Thumb_LoadRelativeAddress<4, 1>,
    &ARM::Thumb_LoadRelativeAddress<4, 1>,
    &ARM::Thumb_LoadRelativeAddress<5, 1>,
    &ARM::Thumb_LoadRelativeAddress<5, 1>,
    &ARM::Thumb_LoadRelativeAddress<5, 1>,
    &ARM::Thumb_LoadRelativeAddress<5, 1>,
    &ARM::Thumb_LoadRelativeAddress<6, 1>,
    &ARM::Thumb_LoadRelativeAddress<6, 1>,
    &ARM::Thumb_LoadRelativeAddress<6, 1>,
    &ARM::Thumb_LoadRelativeAddress<6, 1>,
    &ARM::Thumb_LoadRelativeAddress<7, 1>,
    &ARM::Thumb_LoadRelativeAddress<7, 1>,
    &ARM::Thumb_LoadRelativeAddress<7, 1>,
    &ARM::Thumb_LoadRelativeAddress<7, 1>,
    &ARM::Thumb_AddOffsetSP<0>,
    &ARM::Thumb_AddOffsetSP<0>,
    &ARM::Thumb_AddOffsetSP<1>,
    &ARM::Thumb_AddOffsetSP<1>,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_PushPopRegisters<0, 0>,
    &ARM::Thumb_PushPopRegisters<0, 0>,
    &ARM::Thumb_PushPopRegisters<0, 0>,
    &ARM::Thumb_PushPopRegisters<0, 0>,
    &ARM::Thumb_PushPopRegisters<1, 0>,
    &ARM::Thumb_PushPopRegisters<1, 0>,
    &ARM::Thumb_PushPopRegisters<1, 0>,
    &ARM::Thumb_PushPopRegisters<1, 0>,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_PushPopRegisters<0, 1>,
    &ARM::Thumb_PushPopRegisters<0, 1>,
    &ARM::Thumb_PushPopRegisters<0, 1>,
    &ARM::Thumb_PushPopRegisters<0, 1>,
    &ARM::Thumb_PushPopRegisters<1, 1>,
    &ARM::Thumb_PushPopRegisters<1, 1>,
    &ARM::Thumb_PushPopRegisters<1, 1>,
    &ARM::Thumb_PushPopRegisters<1, 1>,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_LoadStoreMultiple<0, 0>,
    &ARM::Thumb_LoadStoreMultiple<0, 0>,
    &ARM::Thumb_LoadStoreMultiple<0, 0>,
    &ARM::Thumb_LoadStoreMultiple<0, 0>,
    &ARM::Thumb_LoadStoreMultiple<1, 0>,
    &ARM::Thumb_LoadStoreMultiple<1, 0>,
    &ARM::Thumb_LoadStoreMultiple<1, 0>,
    &ARM::Thumb_LoadStoreMultiple<1, 0>,
    &ARM::Thumb_LoadStoreMultiple<2, 0>,
    &ARM::Thumb_LoadStoreMultiple<2, 0>,
    &ARM::Thumb_LoadStoreMultiple<2, 0>,
    &ARM::Thumb_LoadStoreMultiple<2, 0>,
    &ARM::Thumb_LoadStoreMultiple<3, 0>,
    &ARM::Thumb_LoadStoreMultiple<3, 0>,
    &ARM::Thumb_LoadStoreMultiple<3, 0>,
    &ARM::Thumb_LoadStoreMultiple<3, 0>,
    &ARM::Thumb_LoadStoreMultiple<4, 0>,
    &ARM::Thumb_LoadStoreMultiple<4, 0>,
    &ARM::Thumb_LoadStoreMultiple<4, 0>,
    &ARM::Thumb_LoadStoreMultiple<4, 0>,
    &ARM::Thumb_LoadStoreMultiple<5, 0>,
    &ARM::Thumb_LoadStoreMultiple<5, 0>,
    &ARM::Thumb_LoadStoreMultiple<5, 0>,
    &ARM::Thumb_LoadStoreMultiple<5, 0>,
    &ARM::Thumb_LoadStoreMultiple<6, 0>,
    &ARM::Thumb_LoadStoreMultiple<6, 0>,
    &ARM::Thumb_LoadStoreMultiple<6, 0>,
    &ARM::Thumb_LoadStoreMultiple<6, 0>,
    &ARM::Thumb_LoadStoreMultiple<7, 0>,
    &ARM::Thumb_LoadStoreMultiple<7, 0>,
    &ARM::Thumb_LoadStoreMultiple<7, 0>,
    &ARM::Thumb_LoadStoreMultiple<7, 0>,
    &ARM::Thumb_LoadStoreMultiple<0, 1>,
    &ARM::Thumb_LoadStoreMultiple<0, 1>,
    &ARM::Thumb_LoadStoreMultiple<0, 1>,
    &ARM::Thumb_LoadStoreMultiple<0, 1>,
    &ARM::Thumb_LoadStoreMultiple<1, 1>,
    &ARM::Thumb_LoadStoreMultiple<1, 1>,
    &ARM::Thumb_LoadStoreMultiple<1, 1>,
    &ARM::Thumb_LoadStoreMultiple<1, 1>,
    &ARM::Thumb_LoadStoreMultiple<2, 1>,
    &ARM::Thumb_LoadStoreMultiple<2, 1>,
    &ARM::Thumb_LoadStoreMultiple<2, 1>,
    &ARM::Thumb_LoadStoreMultiple<2, 1>,
    &ARM::Thumb_LoadStoreMultiple<3, 1>,
    &ARM::Thumb_LoadStoreMultiple<3, 1>,
    &ARM::Thumb_LoadStoreMultiple<3, 1>,
    &ARM::Thumb_LoadStoreMultiple<3, 1>,
    &ARM::Thumb_LoadStoreMultiple<4, 1>,
    &ARM::Thumb_LoadStoreMultiple<4, 1>,
    &ARM::Thumb_LoadStoreMultiple<4, 1>,
    &ARM::Thumb_LoadStoreMultiple<4, 1>,
    &ARM::Thumb_LoadStoreMultiple<5, 1>,
    &ARM::Thumb_LoadStoreMultiple<5, 1>,
    &ARM::Thumb_LoadStoreMultiple<5, 1>,
    &ARM::Thumb_LoadStoreMultiple<5, 1>,
    &ARM::Thumb_LoadStoreMultiple<6, 1>,
    &ARM::Thumb_LoadStoreMultiple<6, 1>,
    &ARM::Thumb_LoadStoreMultiple<6, 1>,
    &ARM::Thumb_LoadStoreMultiple<6, 1>,
    &ARM::Thumb_LoadStoreMultiple<7, 1>,
    &ARM::Thumb_LoadStoreMultiple<7, 1>,
    &ARM::Thumb_LoadStoreMultiple<7, 1>,
    &ARM::Thumb_LoadStoreMultiple<7, 1>,
    &ARM::Thumb_ConditionalBranch< 0>,
    &ARM::Thumb_ConditionalBranch< 0>,
    &ARM::Thumb_ConditionalBranch< 0>,
    &ARM::Thumb_ConditionalBranch< 0>,
    &ARM::Thumb_ConditionalBranch< 1>,
    &ARM::Thumb_ConditionalBranch< 1>,
    &ARM::Thumb_ConditionalBranch< 1>,
    &ARM::Thumb_ConditionalBranch< 1>,
    &ARM::Thumb_ConditionalBranch< 2>,
    &ARM::Thumb_ConditionalBranch< 2>,
    &ARM::Thumb_ConditionalBranch< 2>,
    &ARM::Thumb_ConditionalBranch< 2>,
    &ARM::Thumb_ConditionalBranch< 3>,
    &ARM::Thumb_ConditionalBranch< 3>,
    &ARM::Thumb_ConditionalBranch< 3>,
    &ARM::Thumb_ConditionalBranch< 3>,
    &ARM::Thumb_ConditionalBranch< 4>,
    &ARM::Thumb_ConditionalBranch< 4>,
    &ARM::Thumb_ConditionalBranch< 4>,
    &ARM::Thumb_ConditionalBranch< 4>,
    &ARM::Thumb_ConditionalBranch< 5>,
    &ARM::Thumb_ConditionalBranch< 5>,
    &ARM::Thumb_ConditionalBranch< 5>,
    &ARM::Thumb_ConditionalBranch< 5>,
    &ARM::Thumb_ConditionalBranch< 6>,
    &ARM::Thumb_ConditionalBranch< 6>,
    &ARM::Thumb_ConditionalBranch< 6>,
    &ARM::Thumb_ConditionalBranch< 6>,
    &ARM::Thumb_ConditionalBranch< 7>,
    &ARM::Thumb_ConditionalBranch< 7>,
    &ARM::Thumb_ConditionalBranch< 7>,
    &ARM::Thumb_ConditionalBranch< 7>,
    &ARM::Thumb_ConditionalBranch< 8>,
    &ARM::Thumb_ConditionalBranch< 8>,
    &ARM::Thumb_ConditionalBranch< 8>,
    &ARM::Thumb_ConditionalBranch< 8>,
    &ARM::Thumb_ConditionalBranch< 9>,
    &ARM::Thumb_ConditionalBranch< 9>,
    &ARM::Thumb_ConditionalBranch< 9>,
    &ARM::Thumb_ConditionalBranch< 9>,
    &ARM::Thumb_ConditionalBranch<10>,
    &ARM::Thumb_ConditionalBranch<10>,
    &ARM::Thumb_ConditionalBranch<10>,
    &ARM::Thumb_ConditionalBranch<10>,
    &ARM::Thumb_ConditionalBranch<11>,
    &ARM::Thumb_ConditionalBranch<11>,
    &ARM::Thumb_ConditionalBranch<11>,
    &ARM::Thumb_ConditionalBranch<11>,
    &ARM::Thumb_ConditionalBranch<12>,
    &ARM::Thumb_ConditionalBranch<12>,
    &ARM::Thumb_ConditionalBranch<12>,
    &ARM::Thumb_ConditionalBranch<12>,
    &ARM::Thumb_ConditionalBranch<13>,
    &ARM::Thumb_ConditionalBranch<13>,
    &ARM::Thumb_ConditionalBranch<13>,
    &ARM::Thumb_ConditionalBranch<13>,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_SoftwareInterrupt,
    &ARM::Thumb_SoftwareInterrupt,
    &ARM::Thumb_SoftwareInterrupt,
    &ARM::Thumb_SoftwareInterrupt,
    &ARM::Thumb_UnconditionalBranch,
    &ARM::Thumb_UnconditionalBranch,
    &ARM::Thumb_UnconditionalBranch,
    &ARM::Thumb_UnconditionalBranch,
    &ARM::Thumb_UnconditionalBranch,
    &ARM::Thumb_UnconditionalBranch,
    &ARM::Thumb_UnconditionalBranch,
    &ARM::Thumb_UnconditionalBranch,
    &ARM::Thumb_UnconditionalBranch,
    &ARM::Thumb_UnconditionalBranch,
    &ARM::Thumb_UnconditionalBranch,
    &ARM::Thumb_UnconditionalBranch,
    &ARM::Thumb_UnconditionalBranch,
    &ARM::Thumb_UnconditionalBranch,
    &ARM::Thumb_UnconditionalBranch,
    &ARM::Thumb_UnconditionalBranch,
    &ARM::Thumb_UnconditionalBranch,
    &ARM::Thumb_UnconditionalBranch,
    &ARM::Thumb_UnconditionalBranch,
    &ARM::Thumb_UnconditionalBranch,
    &ARM::Thumb_UnconditionalBranch,
    &ARM::Thumb_UnconditionalBranch,
    &ARM::Thumb_UnconditionalBranch,
    &ARM::Thumb_UnconditionalBranch,
    &ARM::Thumb_UnconditionalBranch,
    &ARM::Thumb_UnconditionalBranch,
    &ARM::Thumb_UnconditionalBranch,
    &ARM::Thumb_UnconditionalBranch,
    &ARM::Thumb_UnconditionalBranch,
    &ARM::Thumb_UnconditionalBranch,
    &ARM::Thumb_UnconditionalBranch,
    &ARM::Thumb_UnconditionalBranch,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_Undefined,
    &ARM::Thumb_LongBranchLink<0>,
    &ARM::Thumb_LongBranchLink<0>,
    &ARM::Thumb_LongBranchLink<0>,
    &ARM::Thumb_LongBranchLink<0>,
    &ARM::Thumb_LongBranchLink<0>,
    &ARM::Thumb_LongBranchLink<0>,
    &ARM::Thumb_LongBranchLink<0>,
    &ARM::Thumb_LongBranchLink<0>,
    &ARM::Thumb_LongBranchLink<0>,
    &ARM::Thumb_LongBranchLink<0>,
    &ARM::Thumb_LongBranchLink<0>,
    &ARM::Thumb_LongBranchLink<0>,
    &ARM::Thumb_LongBranchLink<0>,
    &ARM::Thumb_LongBranchLink<0>,
    &ARM::Thumb_LongBranchLink<0>,
    &ARM::Thumb_LongBranchLink<0>,
    &ARM::Thumb_LongBranchLink<0>,
    &ARM::Thumb_LongBranchLink<0>,
    &ARM::Thumb_LongBranchLink<0>,
    &ARM::Thumb_LongBranchLink<0>,
    &ARM::Thumb_LongBranchLink<0>,
    &ARM::Thumb_LongBranchLink<0>,
    &ARM::Thumb_LongBranchLink<0>,
    &ARM::Thumb_LongBranchLink<0>,
    &ARM::Thumb_LongBranchLink<0>,
    &ARM::Thumb_LongBranchLink<0>,
    &ARM::Thumb_LongBranchLink<0>,
    &ARM::Thumb_LongBranchLink<0>,
    &ARM::Thumb_LongBranchLink<0>,
    &ARM::Thumb_LongBranchLink<0>,
    &ARM::Thumb_LongBranchLink<0>,
    &ARM::Thumb_LongBranchLink<0>,
    &ARM::Thumb_LongBranchLink<1>,
    &ARM::Thumb_LongBranchLink<1>,
    &ARM::Thumb_LongBranchLink<1>,
    &ARM::Thumb_LongBranchLink<1>,
    &ARM::Thumb_LongBranchLink<1>,
    &ARM::Thumb_LongBranchLink<1>,
    &ARM::Thumb_LongBranchLink<1>,
    &ARM::Thumb_LongBranchLink<1>,
    &ARM::Thumb_LongBranchLink<1>,
    &ARM::Thumb_LongBranchLink<1>,
    &ARM::Thumb_LongBranchLink<1>,
    &ARM::Thumb_LongBranchLink<1>,
    &ARM::Thumb_LongBranchLink<1>,
    &ARM::Thumb_LongBranchLink<1>,
    &ARM::Thumb_LongBranchLink<1>,
    &ARM::Thumb_LongBranchLink<1>,
    &ARM::Thumb_LongBranchLink<1>,
    &ARM::Thumb_LongBranchLink<1>,
    &ARM::Thumb_LongBranchLink<1>,
    &ARM::Thumb_LongBranchLink<1>,
    &ARM::Thumb_LongBranchLink<1>,
    &ARM::Thumb_LongBranchLink<1>,
    &ARM::Thumb_LongBranchLink<1>,
    &ARM::Thumb_LongBranchLink<1>,
    &ARM::Thumb_LongBranchLink<1>,
    &ARM::Thumb_LongBranchLink<1>,
    &ARM::Thumb_LongBranchLink<1>,
    &ARM::Thumb_LongBranchLink<1>,
    &ARM::Thumb_LongBranchLink<1>,
    &ARM::Thumb_LongBranchLink<1>,
    &ARM::Thumb_LongBranchLink<1>,
    &ARM::Thumb_LongBranchLink<1>
};
