name: Build

on:
  push:

jobs:
  build-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: cmd

    steps:
      - uses: actions/checkout@master
        with:
          submodules: true

      - name: Dependencies
        run: |
          vcpkg integrate install
          vcpkg install sdl2:x64-windows
          vcpkg install opengl:x64-windows

      - name: Build
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          msbuild /property:Configuration=ReleaseNoConsole eggvance.sln

      - name: Collect
        run: |
          mkdir upload
          move bin\ReleaseNoConsole\eggvance.exe upload
          move bin\ReleaseNoConsole\SDL2.dll upload

      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: eggvance-windows
          path: upload

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          submodules: true

      - name: Dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev
          sudo apt-get install libgtk-3-dev

      - name: Build
        run: |
          mkdir eggvance/build
          cd eggvance/build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j 4

      - name: Collect
        run: |
          mkdir upload
          mv eggvance/build/eggvance upload

      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: eggvance-linux
          path: upload

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@master
        with:
          submodules: true

      - name: Dependencies
        run: brew install sdl2

      - name: Build
        run: |
          mkdir eggvance/build
          cd eggvance/build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j 4

      - name: Collect
        run: |
          mkdir upload
          mv eggvance/build/eggvance upload

      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: eggvance-macos
          path: upload
